/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.se465.webservice.ui;

import com.se465.webservice.logic.Facade;
import com.se465.webservice.logic.LOCATION_CODES;

/**
 *
 * @author ckopp
 */
public class MainPageUI extends UIFrame {

    /**
     * Creates new form MainPage
     */
    public MainPageUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageTitle_jLabel = new javax.swing.JLabel();
        CurrentLoginPrompt_jLabel = new javax.swing.JLabel();
        RoleContainer_jScrollPane = new javax.swing.JScrollPane();
        CurrentLogin_jTextPane = new javax.swing.JTextPane();
        CitySelector_jComboBox = new javax.swing.JComboBox<>();
        CityPrompt_jLabel = new javax.swing.JLabel();
        LookupStore_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 300));

        PageTitle_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PageTitle_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PageTitle_jLabel.setText("STORE INVENTORY LOOKUP SERVICE");
        PageTitle_jLabel.setName("PageTitle_jLabel"); // NOI18N

        CurrentLoginPrompt_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CurrentLoginPrompt_jLabel.setText("Currently logged in as:");
        CurrentLoginPrompt_jLabel.setName("CurrentLoginPrompt_jLabel"); // NOI18N

        RoleContainer_jScrollPane.setName("RoleContainer_jScrollPane"); // NOI18N

        CurrentLogin_jTextPane.setEditable(false);
        CurrentLogin_jTextPane.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        CurrentLogin_jTextPane.setText("Shopper");
        CurrentLogin_jTextPane.setName("CurrentLogin_jTextPane"); // NOI18N
        RoleContainer_jScrollPane.setViewportView(CurrentLogin_jTextPane);

        CitySelector_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*select a location*", "Minneapolis Location", "Saint Paul Location" }));
        CitySelector_jComboBox.setName("CitySelector_jComboBox"); // NOI18N
        CitySelector_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitySelector_jComboBoxActionPerformed(evt);
            }
        });

        CityPrompt_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CityPrompt_jLabel.setText("Please select a city:");
        CityPrompt_jLabel.setName("CityPrompt_jLabel"); // NOI18N

        LookupStore_jButton.setText("Lookup");
        LookupStore_jButton.setName("LookupStore_jButton"); // NOI18N
        LookupStore_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LookupStore_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentLoginPrompt_jLabel)
                            .addComponent(CityPrompt_jLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CitySelector_jComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 216, Short.MAX_VALUE)
                            .addComponent(RoleContainer_jScrollPane)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PageTitle_jLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LookupStore_jButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PageTitle_jLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RoleContainer_jScrollPane)
                    .addComponent(CurrentLoginPrompt_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CitySelector_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityPrompt_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(LookupStore_jButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CitySelector_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitySelector_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CitySelector_jComboBoxActionPerformed

    private void LookupStore_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LookupStore_jButtonActionPerformed
        // TODO add your handling code here:
        if (this.CitySelector_jComboBox.getSelectedIndex() != 0) {
            Facade.getInstance().receiveCity((String) this.CitySelector_jComboBox.getSelectedItem());
            this.conceal();
        }

    }//GEN-LAST:event_LookupStore_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityPrompt_jLabel;
    private javax.swing.JComboBox<String> CitySelector_jComboBox;
    private javax.swing.JLabel CurrentLoginPrompt_jLabel;
    private javax.swing.JTextPane CurrentLogin_jTextPane;
    private javax.swing.JButton LookupStore_jButton;
    private javax.swing.JLabel PageTitle_jLabel;
    private javax.swing.JScrollPane RoleContainer_jScrollPane;
    // End of variables declaration//GEN-END:variables
}
