/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.se465.webservice.ui;

/**
 *
 * @author ckopp
 */
public class ResultsUI extends UIFrame {

    /**
     * Creates new form ResultsUI
     */
    private String result;

    public ResultsUI() {
        initComponents();
    }

    public ResultsUI(String result) {
        this();
        this.result = result;
    }

    @Override
    public void render() {
        super.render(); //To change body of generated methods, choose Tools | Templates.
        this.Results_jTextArea.setText(this.result);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton_jButton = new javax.swing.JButton();
        PageTitle_jLabel = new javax.swing.JLabel();
        Results_jScrollPane = new javax.swing.JScrollPane();
        Results_jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackButton_jButton.setText("< Go Back");
        BackButton_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton_jButtonActionPerformed(evt);
            }
        });

        PageTitle_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PageTitle_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PageTitle_jLabel.setText("RESULTS FROM INVENTORY QUERY");

        Results_jTextArea.setEditable(false);
        Results_jTextArea.setColumns(20);
        Results_jTextArea.setRows(5);
        Results_jScrollPane.setViewportView(Results_jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Results_jScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackButton_jButton)
                            .addComponent(PageTitle_jLabel))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PageTitle_jLabel)
                .addGap(18, 18, 18)
                .addComponent(Results_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BackButton_jButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButton_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton_jButtonActionPerformed
        // TODO add your handling code here:
        UIController.getInstance().displayNextFrame(this, new MainPageUI());
    }//GEN-LAST:event_BackButton_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton_jButton;
    private javax.swing.JLabel PageTitle_jLabel;
    private javax.swing.JScrollPane Results_jScrollPane;
    private javax.swing.JTextArea Results_jTextArea;
    // End of variables declaration//GEN-END:variables
}
